name: Update Requirements on Deploy Branch

on:
  push:
    branches:
      - main  # Trigger when pushing to main

jobs:
  ci:
    env:
      UV_SYSTEM_PYTHON: true
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main # Checkout the main branch to get latest changes

      # Step 2: Merge main into deploy
      - name: Force push main to deploy
        run: |
          git push --force origin main:deploy  # Force push main to deploy

      # Step 3: Set up uv
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      # Step 4: Install the project
      - name: Install the project
        run: uv sync --all-extras --dev --locked

      # Step 5: Run uv commands to generate requirements
      - name: Run uv commands to generate requirements
        run: |
          uv export --no-hashes -o requirements.txt
          uvx --from rsconnect-python --python .venv/bin/python rsconnect write-manifest shiny . --entrypoint pyshinywikidata.app:app

      # Step 6: Commit and push updated requirements file (if it changes)
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update requirements on new commit from main" || echo "No changes to commit"
          git push origin deploy  # Push to deploy branch, using force because of diverging branches
